on:
  pull_request:
    types:
      - opened
    branches:
      - 'icona-deploy-**' 
   
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - uses: actions/checkout@v3

      - name: Read icona config yaml
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: '.icona/config.yml'          # File to read from
          key-path: '["icon-frame-id", "figma-file-key"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
