on:
  pull_request:
    types:
      - opened
    # branches:
    #   - 'icona-deploy-**'
    # paths:
    #   - '.icona/release.md'
   
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - uses: actions/checkout@v3
     
      - name: Extract SVG from figma
        uses: junghyeonsu/figma-svg-extract-action@v0.0.1
        with:
          figma-file-key: jcGX8Gi8Vq8brdeou6QJ6X
          figma-icon-frame-id: 672:688
          figma-token: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
