on:
  pull_request:
    types:
      - opened
    # branches:
    #   - 'icona-deploy-**'
    # paths:
    #   - '.icona/release.md'
   
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - uses: actions/checkout@v3

      - name: Read icona config yaml
        id: yaml-data
        uses: the-coding-turtle/ga-yaml-parser@v0.1.2
        with:
          file: '.icona/config.yml'
          export_to_envs: true

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.result }}"
